### ISSUE TITLE
Voir TACAN +Radio tancker

### ISSUE THREAD

**Issue by davidp57** [VEAF/VEAF-Open-Training-Mission-Syria#9]
from [VEAF]Zip on Discord

**Comment by davidp57** [comment]
Données vérifiées, à tester en vol (c'était correct)

**Comment by antoinethomas** [comment]
Suite à la mission de lundi où on a pas pu ravitaillé sur le Tanker Sud j'ai corrigé un soucis d'advanced waypoint. Il manquait le "-tanker a" dans le premier waypoint du Tanker MPRS Sud (T2S)
